// vue_demo/src/components/PopWin.vue
<template>
  <div
    class="popwin_container"
    v-if="show"
    @mousewheel.stop.prevent
    @click.self="cancel"
  >
    <div class="popwin" :style="{ left: left + 'px', top: top + 'px' }">
      <i class="icon-close" @click="cancel"></i>
      <div :class="['arrow_box', { down: !isUp }]"></div>
      <div class="title">Separate multiple resource name with commas</div>
      <input
        type="text"
        class="resource_input"
        placeholder="e.g. Chrome,Firefox"
        v-model="resources"
      />
      <div class="popwin_buttons">
        <div class="sure blue_btn" @click="addResource">Add Resources</div>
        <div class="cancel gray_btn" @click="cancel">Cancel</div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "PopWin",
  data() {
    return {
      resources: "",
      top: 0,
      left: 0,
      show: false,
      isUp: true,
      callback: null,
    };
  },
  methods: {
    addResource() {
      // TODO: resource length check
      this.resources = this.resources.trim();
      const arr = this.resources.split(",").filter((ele) => ele.trim());
      if (!arr.length) return;
      this.callback && this.callback(arr);
      this.cancel();
    },
    cancel() {
      this.show = false;
      this.resources = "";
      this.callback = null;
    },
  },
};
</script>

<style lang="less" scoped>
@arrowBaseSize: 12px;
.arrow_style {
  position: absolute;
  width: 0;
  height: 0;
  border-bottom: 2 * @arrowBaseSize solid @blueColor;
  border-left: @arrowBaseSize solid transparent;
  border-right: @arrowBaseSize solid transparent;
}
.popwin_container {
  position: fixed;
  z-index: 2000;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  .popwin {
    background: #fff;
    position: absolute;
    width: 570px;
    border: 1px solid @blueColor;
    padding: 15px;
    box-sizing: border-box;
    .icon-close {
      color: @blueColor;
      font-size: 25px;
      position: absolute;
      top: 10px;
      right: 20px;
      cursor: pointer;
    }
    .arrow_box:extend(.arrow_style) {
      top: -25px;
      left: 20px;
      &.down {
        transform: rotate(180deg);
        top: auto;
        bottom: -25px;
      }
      &::after:extend(.arrow_style) {
        content: "";
        position: absolute;
        transform: translate(-50%, 2px);
        border-bottom: 2 * @arrowBaseSize solid #fff;
      }
    }
    input {
      margin-top: 15px;
      width: 100%;
      height: 30px;
      line-height: 30px;
      padding: 0 20px;
      box-sizing: border-box;
      border: 1px solid #999;
      border-radius: 4px;
      &:focus {
        border: 1px solid #999;
        outline: none;
      }
    }
    .popwin_buttons {
      margin-top: 15px;
      div {
        width: 110px;
        text-align: center;
        display: inline-block;
        margin-right: 20px;
      }
    }
  }
}

@media screen and (max-width: 1204px) {
  .popwin_container {
    background-color: rgba(0, 0, 0, .3);
  }
  .popwin {
    left: 50%!important;
    top: 150px!important;
    transform: translateX(-50%);
  }
  .arrow_box {
    display: none;
  }
}
@media screen and (max-width: 768px) {
  .popwin_container {
    .popwin {
      width: 100%;
      padding-top: 50px;
      .popwin_buttons {
        .gray_btn {
          display: none;
        }
        .blue_btn {
          width: 93%;
        }
      }
    }
  }
}

  
</style>

// react_demo/src/components/Popwin/index.js
import React, { useState, useRef, useEffect } from "react";
import ReactDOM from "react-dom";
import "./index.scss";

function Popwin({ top, left, fn }) {
  const windowHeight = window.innerHeight;
  left = left - 17;
  top = top + 50;
  let isUp = true;
  if (top > windowHeight - 150) {
    top = top - 220;
    isUp = false;
  }
  let callback = fn;
  const [resources, setResources] = useState("");
  const container = useRef(null);
  function addResource() {
    // 此处最好校验名称长度
    setResources(resources.trim());
    const arr = resources.split(",").filter((ele) => ele.trim());
    if (!arr.length) return;
    callback && callback(arr);
    cancel();
  }

  function cancel() {
    setResources("");
    callback = null;
    Popwin.hide();
  }

  function stopProp(e, fn) {
    e.stopPropagation();
    e.nativeEvent.stopImmediatePropagation();
    fn && fn();
  }

  useEffect(() => {
    container.current.addEventListener(
      "mousewheel",
      (e) => {
        e.preventDefault();
      },
      {
        passive: false,
      }
    );
  }, []);

  return (
    <div className="popwin_container" ref={container} onClick={() => cancel()}>
      <div
        className="popwin"
        style={{ left: left + "px", top: top + "px" }}
        onClick={(e) => stopProp(e)}
      >
        <i className="icon-close" onClick={() => cancel()}></i>
        <div className={`arrow_box ${isUp ? "" : "down"}`}></div>
        <div className="title">Separate multiple resource name with commas</div>
        <input
          type="text"
          className="resource_input"
          placeholder="Input value"
          value={resources}
          onChange={(e) => setResources(e.target.value)}
        />
        <div className="popwin_buttons">
          <div className="sure blue_btn" onClick={() => addResource()}>
            Add Resources
          </div>
          <div className="cancel gray_btn" onClick={() => cancel()}>
            Cancel
          </div>
        </div>
      </div>
    </div>
  );
}

Popwin.show = function (props) {
  this.dom = document.createElement("div");
  document.body.append(this.dom);
  ReactDOM.render(<Popwin {...props} />, this.dom);
};

Popwin.hide = function () {
  this.dom && ReactDOM.unmountComponentAtNode(this.dom);
  this.dom && this.dom.parentNode && this.dom.parentNode.removeChild(this.dom);
};
export default Popwin;
